import { useCallback, useEffect, useMemo, useState } from 'react';
import NumberFlow from '@number-flow/react';
import { MeshGradient } from '@paper-design/shaders-react';
import { createRoot } from 'react-dom/client';
import '../../design-system/base.css';
import '../../design-system/components.css';
import logoUrl from '../../design-system/assets/logo.png';
import danAvatar from '../../assets/images/dan_1_cutout.png'; import jamesAvatar from '../../assets/images/james_1_cutout.png'; import johnAvatar from '../../assets/images/john_1_cutout.png'; import mattAvatar from '../../assets/images/matt_1_cutout.png'; import peterAvatar from '../../assets/images/peter_1_cutout.png';
import { AtlasMap, type AtlasMapDestination } from './AtlasMap.js'; import './app.css'; import { signInWithGoogle } from './firebase.js';
type User = 'dan'|'james'|'john'|'matt'|'peter'; type Activity={id:string;title:string;description:string;imageUrl?:string|null}; type Progress={comparisons:number;minimum:number;maximum:number;estimatedCompletion:number}; type Next={complete:true}|{complete:false;progress:Progress;activityA:Activity;activityB:Activity}; type Photo={path:string;alt:string;photographerName:string;photographerUrl:string;sourceUrl:string}; type AtlasDestination=AtlasMapDestination&{country:string;tagline:string;novemberWeather:string;travelFriction:number;gallery:Photo[]}; type GroupResults={group:Array<{rank:number;id:string;name:string;country:string;imageUrl:string;polarization:number;groupScore:number}>;members:Array<{user:User;topThree:Array<{rank:number;id:string;name:string;imageUrl:string}>}>}; type Screen='welcome'|'character'|'game'|'ready'|'atlas'|'results';
const travelers=[{id:'dan',name:'Dan',role:'Trip wrangler',image:danAvatar,accent:'amber'},{id:'james',name:'James',role:'Curiosity engine',image:jamesAvatar,accent:'terra'},{id:'john',name:'John',role:'Good-times scout',image:johnAvatar,accent:'blue'},{id:'matt',name:'Matt',role:'Trail negotiator',image:mattAvatar,accent:'olive'},{id:'peter',name:'Peter',role:'Wildcard energy',image:peterAvatar,accent:'violet'}] as const;
const progressMessage=(n:number)=>n<8?'Finding your trip rhythm.':n<18?'You’re on a roll.':n<24?'Almost there — just a few gut calls left.':'Signal acquired. Checking the final shape.';
const api=async<T,>(path:string,user:User,token?:string,init?:RequestInit):Promise<T>=>{const headers=new Headers(init?.headers);headers.set('Content-Type','application/json');headers.set(token?'Authorization':'X-Demo-User',token?`Bearer ${token}`:user);const response=await fetch(path,{...init,headers});if(!response.ok)throw new Error((await response.json()).error??'Something went wrong.');return response.json();};
function Ambient(){return <div className="ambient-field" aria-hidden="true"><MeshGradient colors={['#d4924d','#4b7eb2','#c04f3d','#6d8c4a']} distortion={.7} swirl={.25} speed={.12} style={{width:'100%',height:'100%'}}/></div>}; function Avatar({id,large=false}:{id:User;large?:boolean}){const p=travelers.find(x=>x.id===id)!;return <img className={`avatar-art ${large?'avatar-art--large':''}`} src={p.image} alt=""/>}
function App(){const[screen,setScreen]=useState<Screen>('welcome'),[user,setUser]=useState<User>('dan'),[selected,setSelected]=useState<User>(),[token,setToken]=useState<string>(),[next,setNext]=useState<Next>(),[atlas,setAtlas]=useState<AtlasDestination[]>([]),[active,setActive]=useState(''),[results,setResults]=useState<GroupResults>(),[picked,setPicked]=useState(''),[loading,setLoading]=useState(false),[gallery,setGallery]=useState(0),[toast,setToast]=useState(''),[error,setError]=useState('');const dest=useMemo(()=>atlas.find(x=>x.id===active)??atlas[0],[atlas,active]);const person=travelers.find(x=>x.id===user)!;
const load=useCallback(async()=>{try{setLoading(true);setNext(await api<Next>('/v1/comparison/next',user,token));}catch(e){setError(e instanceof Error?e.message:'Unable to load a choice.')}finally{setLoading(false)}},[user,token]);useEffect(()=>{if(screen==='game')void load()},[screen,load]);const select=(id:string)=>{setActive(id);setGallery(0)};
const signIn=async()=>{if(!selected)return;if(!import.meta.env.PROD){setUser(selected);setScreen('game');return}try{const t=await signInWithGoogle(),s=await api<{user:User}>('/v1/session',selected,t);setToken(t);setUser(s.user);if(s.user!==selected)throw new Error(`That account belongs to ${s.user}.`);setScreen('game')}catch(e){setError(e instanceof Error?e.message:'Google sign-in failed.')}};
const choose=async(winner:string)=>{if(!next||next.complete||picked)return;setPicked(winner);try{await api('/v1/comparisons',user,token,{method:'POST',body:JSON.stringify({activityA:next.activityA.id,activityB:next.activityB.id,winner})});setTimeout(()=>{setPicked('');void load()},180)}catch(e){setPicked('');setError(e instanceof Error?e.message:'Unable to save your choice.')}};
const openAtlas=async()=>{try{setLoading(true);const r=await api<{destinations:AtlasDestination[]}>('/v1/atlas',user,token);setAtlas(r.destinations);select(r.destinations[0]?.id??'');setScreen('atlas')}catch(e){setError(e instanceof Error?e.message:'Unable to prepare your atlas.')}finally{setLoading(false)}};const showResults=async()=>{try{setResults(await api<GroupResults>('/v1/results/group',user,token));setScreen('results')}catch(e){setError(e instanceof Error?e.message:'The whole crew has not finished yet.')}};const reveal=async()=>{try{await api('/v1/reveal',user,token,{method:'POST'});await showResults()}catch(e){setError(e instanceof Error?e.message:'Unable to open the reveal.')}};
if(screen==='welcome')return <main className="welcome-shell screen-enter"><Ambient/><section className="welcome"><img src={logoUrl} alt="Let's Go Somewhere" className="logo"/><p className="eyebrow">Five travelers. One real answer.</p><h1>Let the trip<br/><em>choose itself.</em></h1><p className="lede">A destination-blind game for deciding where your group should go. Choose the experiences that pull you in; we keep the places secret until it counts.</p><div className="how-it-works"><span><b>01</b> Pick your traveler</span><span><b>02</b> Make gut-call choices</span><span><b>03</b> Explore the contenders</span></div><button className="lgs-button lgs-button--primary welcome-cta" onClick={()=>setScreen('character')}>Meet the crew →</button></section></main>;
if(screen==='character')return <main className="character-shell screen-enter"><header className="topbar"><button className="back-button" onClick={()=>setScreen('welcome')} aria-label="Back">←</button><img src={logoUrl} alt="Let's Go Somewhere" className="topbar-logo"/><span>Choose your traveler</span></header><section className="character-intro"><p className="eyebrow">The roster</p><h1>Pick your<br/>adventure pal.</h1><p className="lede">Click your traveler, then sign in with the Google account on the roster.</p></section><section className="traveler-roster">{travelers.map(p=><button key={p.id} className={`traveler traveler--${p.accent} ${selected===p.id?'traveler--selected':''}`} onClick={()=>{setSelected(p.id);setToast(`${p.name} is ready to roll.`);setTimeout(()=>setToast(''),1800)}} aria-pressed={selected===p.id}><i/><Avatar id={p.id} large/><span><strong>{p.name}</strong><small>{p.role}</small></span></button>)}</section>{toast&&<p className="selection-toast" role="status">✦ {toast}</p>}<div className="character-action"><button className="lgs-button lgs-button--primary" disabled={!selected} onClick={()=>void signIn()}>{selected?`Roll as ${travelers.find(x=>x.id===selected)?.name}`:'Choose your traveler'} →</button>{error&&<p className="error">{error}</p>}</div></main>;
if(screen==='results'&&results){const winner=results.group[0];return <main className="verdict-shell screen-enter"><Ambient/><header className="verdict-topbar"><img src={logoUrl} alt="Let's Go Somewhere" className="topbar-logo"/><span className="eyebrow">The envelope, opened</span></header><section className="verdict-hero" style={{backgroundImage:`linear-gradient(90deg,rgba(24,20,17,.94),rgba(24,20,17,.25)),url(${winner.imageUrl})`}}><p className="eyebrow">The crew’s shared favorite</p><h1>The verdict:<br/><em>{winner.name}.</em></h1><p>{winner.country} — a strong fit without leaving anyone behind.</p></section><section className="verdict-ranking"><p className="eyebrow">The short list</p>{results.group.map(x=><article key={x.id}><img src={x.imageUrl} alt=""/><span>#{x.rank}</span><div><h2>{x.name}</h2><p>Group fit <NumberFlow value={Math.round(x.groupScore*100)}/></p></div><b>{x.polarization<.18?'Consensus favorite':'Worth a debate'}</b></article>)}</section><section className="crew-votes"><p className="eyebrow">The party’s picks</p><h2>Every traveler’s top three.</h2><div>{results.members.map(m=><article key={m.user}><Avatar id={m.user} large/><h3>{travelers.find(x=>x.id===m.user)?.name}</h3><ol>{m.topThree.map(x=><li key={x.id}><span>{x.rank}</span><img src={x.imageUrl} alt=""/><b>{x.name}</b></li>)}</ol></article>)}</div></section></main>}
if(screen==='atlas')return <main className="atlas-page screen-enter"><Ambient/><header className="atlas-toolbar"><img src={logoUrl} alt="Let's Go Somewhere" className="topbar-logo"/><div><p className="eyebrow">Atlas unlocked</p><b>Every place is still in play.</b></div><div className="traveler-chip"><Avatar id={user}/>{person.name}</div></header><section className="atlas-map-stage"><AtlasMap destinations={atlas} activeId={active} onSelect={select}/>{dest&&<aside className="atlas-drawer"><button onClick={()=>setActive('')} aria-label="Close details">×</button><p className="eyebrow">Now exploring</p><h1>{dest.name}</h1><p className="country">{dest.country}</p><p>{dest.tagline}</p><div className="atlas-facts"><div><span>November</span><b>{dest.novemberWeather}</b></div><div><span>Travel effort</span><b>{dest.travelFriction}/5</b><small>1 = easy route · 5 = big expedition</small></div></div><div className="atlas-filmstrip">{dest.gallery.map((p,i)=><button key={p.path} className={i===gallery?'is-active':''} onClick={()=>setGallery(i)}><img src={p.path} alt={i===gallery?p.alt:''}/></button>)}</div><p className="atlas-credit">Photo by <a href={dest.gallery[gallery]?.photographerUrl}>{dest.gallery[gallery]?.photographerName}</a> on Unsplash</p></aside>}</section><section className="atlas-list atlas-list--v4">{atlas.map(x=><button key={x.id} onClick={()=>select(x.id)}><img src={x.gallery[0].path} alt=""/><b>{x.name}</b><small>{x.country}</small></button>)}</section><section className="reveal-callout"><div><p className="eyebrow">Still sealed</p><h2>The choices are doing their quiet work.</h2><p>We’ll show the crew’s result when every traveler has finished.</p></div><div>{user==='dan'&&<button className="lgs-button lgs-button--primary" onClick={()=>void reveal()}>Open the group reveal</button>}<button className="lgs-button lgs-button--secondary" onClick={()=>void showResults()}>Check the reveal</button></div>{error&&<p className="error">{error}</p>}</section></main>;
if(screen==='ready'||next?.complete)return <main className="ready-shell screen-enter"><p className="eyebrow">Choices complete</p><h1>Your instincts are<br/>on the <em>map.</em></h1><p className="lede">You made the calls. Now meet the places you were responding to—while every ranking stays under wraps.</p><button className="lgs-button lgs-button--primary" onClick={()=>void openAtlas()}>Open the trip atlas →</button>{loading&&<p>Unfolding your atlas…</p>}{error&&<p className="error">{error}</p>}</main>;
const acts=next&&!next.complete?[next.activityA,next.activityB]:[],progress=next&&!next.complete?next.progress:{comparisons:0,minimum:24,maximum:40,estimatedCompletion:0};return <main className="game-shell screen-enter"><header className="game-topbar"><img src={logoUrl} alt="Let's Go Somewhere" className="topbar-logo"/><div className="turn-meta"><Avatar id={user}/>{person.name}'s turn</div></header><section className="game-heading"><p className="eyebrow">Trust your first instinct</p><div className="game-title-row"><h1>Which calls to you?</h1><span><NumberFlow value={progress.comparisons}/> answered</span></div><div className="game-progress"><i style={{width:`${progress.estimatedCompletion*100}%`}}/></div><p className="progress-message">{progressMessage(progress.comparisons)} <b><NumberFlow value={progress.minimum}/> minimum · up to <NumberFlow value={progress.maximum}/></b></p></section>{loading&&!acts.length?<p className="topo-loader">Loading the next possibility…</p>:<section className="choice-stage">{acts.map((a,i)=><button key={a.id} className={`choice-card choice-card--${i} ${picked===a.id?'choice-card--picked':''}`} onClick={()=>void choose(a.id)} disabled={!!picked}><i className="choice-photo" style={{backgroundImage:`url(${a.imageUrl})`}}/><i className="choice-photo-wash"/><span className="choice-pick">I’d rather… ↗</span><span className="choice-copy"><strong>{a.title}</strong><small>{a.description}</small></span></button>)}</section>}<div className="or-divider"><span/>OR<span/></div></main>}
createRoot(document.getElementById('root')!).render(<App/>);
