import { useCallback, useEffect, useState } from 'react';
import { createRoot } from 'react-dom/client';
import '../../design-system/base.css';
import '../../design-system/components.css';
import logoUrl from '../../design-system/assets/logo.png';
import './app.css';

type Activity = { id: string; title: string; description: string };
type Next = { complete: true } | { complete: false; progress: { comparisons: number; estimatedCompletion: number }; activityA: Activity; activityB: Activity };
const api = async <T,>(path: string, user: string, init?: RequestInit): Promise<T> => { const response = await fetch(path, { ...init, headers: { 'Content-Type': 'application/json', 'X-Demo-User': user, ...init?.headers } }); if (!response.ok) throw new Error((await response.json()).error ?? 'Something went wrong.'); return response.json(); };

function App() {
  const [user, setUser] = useState('dan'); const [started, setStarted] = useState(false); const [next, setNext] = useState<Next>(); const [profile, setProfile] = useState<Record<string, number>>(); const [results, setResults] = useState<Array<{ id: string; name: string; country: string; preferenceScore: number }>>(); const [error, setError] = useState('');
  const load = useCallback(async () => { try { setError(''); setNext(await api<Next>('/v1/comparison/next', user)); } catch (cause) { setError(cause instanceof Error ? cause.message : 'Unable to load a choice.'); } }, [user]);
  useEffect(() => { if (started && !profile) void load(); }, [started, profile, load]);
  const choose = async (winner: string) => { if (!next || next.complete) return; try { await api('/v1/comparisons', user, { method: 'POST', body: JSON.stringify({ activityA: next.activityA.id, activityB: next.activityB.id, winner }) }); await load(); } catch (cause) { setError(cause instanceof Error ? cause.message : 'Unable to save your choice.'); } };
  const showProfile = async () => { try { setProfile((await api<{ attributes: Record<string, number> }>('/v1/profile', user)).attributes); } catch (cause) { setError(cause instanceof Error ? cause.message : 'Unable to prepare profile.'); } };
  const showResults = async () => { try { setResults((await api<{ results: Array<{ id: string; name: string; country: string; preferenceScore: number }> }>('/v1/results/me', user)).results); } catch (cause) { setError(cause instanceof Error ? cause.message : 'The group reveal is still closed.'); } };
  const openGroupReveal = async () => { try { await api('/v1/reveal', user, { method: 'POST' }); await showResults(); } catch (cause) { setError(cause instanceof Error ? cause.message : 'Unable to open the reveal.'); } };
  if (!started) return <main className="landing"><img src={logoUrl} alt="Let's Go Somewhere" className="logo" /><p className="eyebrow">A destination-blind trip game</p><h1>Where should we actually go?</h1><p className="lede">Pick between things you could do. We won’t tell you where they are until the reveal.</p><label className="identity">Local development identity<select value={user} onChange={(event) => setUser(event.target.value)}>{['dan', 'james', 'john', 'matt', 'peter'].map((name) => <option key={name}>{name}</option>)}</select></label><button className="lgs-button lgs-button--primary" onClick={() => setStarted(true)}>Start the game</button><p className="hint">Usually 28–35 quick choices. Your progress is saved.</p></main>;
  if (results) return <main className="panel"><p className="eyebrow">Group reveal</p><h1>Here’s where you actually want to go.</h1><ol className="result-list">{results.map((result, index) => <li key={result.id} className="lgs-card"><span className="lgs-badge">#{index + 1} match</span><h2>{result.name}, {result.country}</h2><p>Preference score <strong>{Math.round(result.preferenceScore)}</strong></p></li>)}</ol></main>;
  if (profile) return <main className="panel"><p className="eyebrow">Preference profile</p><h1>Okay. We know your type.</h1><p className="lede">You’ve finished choosing. Your destinations stay hidden until the group reveal opens.</p>{error && <p role="alert" className="error">{error}</p>}<section className="attribute-list" aria-label="Your preference signals">{Object.entries(profile).sort((a, b) => b[1] - a[1]).map(([name, value]) => <div key={name}><span>{name.replace(/([A-Z])/g, ' $1')}</span><meter min="-100" max="100" value={value} aria-label={`${name} signal`}/></div>)}</section><div className="lgs-card waiting"><span className="lgs-badge lgs-badge--success">Study complete</span><h2>Waiting for the group</h2><p>We’ll reveal named destinations once every traveler finishes, or the organizer opens the gate.</p><button className="lgs-button lgs-button--secondary" onClick={() => void showResults()}>Check group reveal</button>{user === 'dan' && <button className="lgs-button lgs-button--primary" onClick={() => void openGroupReveal()}>Open the reveal for the group</button>}</div></main>;
  if (next?.complete) return <main className="panel"><p className="eyebrow">Analysis ready</p><h1>Your choices are in.</h1><button className="lgs-button lgs-button--primary" onClick={() => void showProfile()}>See my preference profile</button></main>;
  return <main className="panel"><header><p className="eyebrow">Learning your trip</p><div className="progress-row"><span>About {Math.round((next?.progress.estimatedCompletion ?? 0) * 100)}% there</span><div className="lgs-progress" aria-label="Approximate study progress"><div className="lgs-progress__value" style={{ width: `${(next?.progress.estimatedCompletion ?? 0) * 100}%` }}/></div></div></header><h1>Which sounds better?</h1>{error && <p role="alert" className="error">{error}</p>}<section className="choices" aria-label="Choose the activity that sounds more fun">{next && [next.activityA, next.activityB].map((activity, index) => <button key={activity.id} className="lgs-card lgs-card--interactive lgs-activity-card" onClick={() => void choose(activity.id)}><span className="lgs-activity-card__label">Option {index === 0 ? 'A' : 'B'}</span><span className="lgs-activity-card__title">{activity.title}</span><span className="lgs-activity-card__description">{activity.description}</span><span className="pick">Pick this</span></button>)}</section></main>;
}
createRoot(document.getElementById('root')!).render(<App />);
